version: '3.8'

services:
  web:
    container_name: kanban-board-api-test
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
  
  postgres:
    container_name: kanban-board-postgres-test
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres