version: '3.8'

services:
  web:
    container_name: kanban-board-api
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
  
  postgres:
    container_name: kanban-board-postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: