---
version: '2'

checks:
  identical-code:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 75
  method-lines:
    config:
      threshold: 250

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
