version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kanri-front-dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 127.0.0.1:5173:5173
    container_name: kanri-front-dev