version: '3.8'

services:
  app:
    image: kanban-board-app
    container_name: kanban-board-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
