version: '3.8'

services:
  app:
    image: kanban-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: kanban-frontend-dev