name: E2E Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build project for eslint
        run: npm install
      - name: Run eslint
        run: npm run lint

  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare test data and start the application
        run: docker-compose -f docker-compose.ci.yml up -d

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:run
          start: npm i
          wait-on: 'http://localhost:5173/'
          wait-on-timeout: 120
